version: '3.8'

services:
  app:
    build: .
    container_name: crypto_tracker_app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/crypto_tracker
    volumes:
      - .:/app
    command: python run_pipeline.py
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: crypto_tracker_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crypto_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: